services:
  content-downloader:
    build: .
    environment:
      - TRW_EMAIL=${TRW_EMAIL}
      - TRW_PASSWORD=${TRW_PASSWORD}
      - DROPBOX_APP_KEY=${DROPBOX_APP_KEY}
      - DROPBOX_APP_SECRET=${DROPBOX_APP_SECRET}
      - DROPBOX_REFRESH_TOKEN=${DROPBOX_REFRESH_TOKEN}
      - JIUJITSU_EMAIL=${JIUJITSU_EMAIL}
      - JIUJITSU_PASSWORD=${JIUJITSU_PASSWORD}
    volumes:
      - ./:/app
